#!/usr/bin/env bash
set -Eeuo pipefail

# Shared pipeline settings. Edit these values if you want to move the project,
# change ports, or use a different stable Ollama tag.

BASE_DIR="/home/kgaer/code/OpenclawOllama"
GGUF_SEARCH_DIR="$BASE_DIR"

OLLAMA_MODEL_TAG="qwen-local:latest"
OLLAMA_TEMPLATE_BASE_MODEL="qwen2.5:3b"
OLLAMA_BIND_HOST="127.0.0.1"
OLLAMA_PORT="11434"

OPENCLAW_PORT="18789"
OPENCLAW_BIND_MODE="loopback"
OPENCLAW_WORKSPACE="$BASE_DIR/workspace"

TEST_PROMPT="Reply with exactly: OPENCLAW_OLLAMA_OK"
OPENCLAW_AGENT_SMOKE_TO="+15555550125"
OPENCLAW_AGENT_SMOKE_PROMPT="Respond in plain text only. Do not call any tools. Reply with exactly: GATEWAY_POSTFIX_OK"
OPENCLAW_AGENT_SMOKE_EXPECT="GATEWAY_POSTFIX_OK"

LOG_DIR="$BASE_DIR/logs"
RUN_DIR="$BASE_DIR/run"
STATE_DIR="$BASE_DIR/state"
GENERATED_DIR="$BASE_DIR/generated"
LOCAL_BIN_DIR="$HOME/.local/bin"
LOCAL_OLLAMA_INSTALL_DIR="$HOME/.local/share/ollama-app"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
OLLAMA_USER_SERVICE_NAME="ollama-local.service"
OPENCLAW_SYSTEMD_SERVICE_NAME="openclaw-gateway.service"

GENERATED_MODELFILE="$GENERATED_DIR/Modelfile"
GENERATED_GGUF_LINK="$GENERATED_DIR/current-model.gguf"

CURRENT_GGUF_FILE="$STATE_DIR/current.gguf"
CURRENT_MODELFILE_FILE="$STATE_DIR/current-modelfile.txt"

OLLAMA_SERVICE_MODE_FILE="$STATE_DIR/ollama-service-mode"
OPENCLAW_SERVICE_MODE_FILE="$STATE_DIR/openclaw-service-mode"

OLLAMA_PID_FILE="$RUN_DIR/ollama.pid"
OPENCLAW_PID_FILE="$RUN_DIR/openclaw-gateway.pid"

OLLAMA_LOG_FILE="$LOG_DIR/ollama.log"
OPENCLAW_LOG_FILE="$LOG_DIR/openclaw-gateway.log"
OPENCLAW_GATEWAY_TOKEN_FILE="$STATE_DIR/openclaw-gateway.token"

OPENCLAW_STATE_HOME="$HOME/.openclaw"
OPENCLAW_CONFIG_FILE="$OPENCLAW_STATE_HOME/openclaw.json"

OLLAMA_BASE_URL="http://${OLLAMA_BIND_HOST}:${OLLAMA_PORT}"
OPENCLAW_MODEL_REF="ollama/${OLLAMA_MODEL_TAG}"
OPENCLAW_UI_URL="http://127.0.0.1:${OPENCLAW_PORT}/"

export BASE_DIR
export GGUF_SEARCH_DIR
export OLLAMA_MODEL_TAG
export OLLAMA_TEMPLATE_BASE_MODEL
export OLLAMA_BIND_HOST
export OLLAMA_PORT
export OPENCLAW_PORT
export OPENCLAW_BIND_MODE
export OPENCLAW_WORKSPACE
export TEST_PROMPT
export OPENCLAW_AGENT_SMOKE_TO
export OPENCLAW_AGENT_SMOKE_PROMPT
export OPENCLAW_AGENT_SMOKE_EXPECT
export LOG_DIR
export RUN_DIR
export STATE_DIR
export GENERATED_DIR
export LOCAL_BIN_DIR
export LOCAL_OLLAMA_INSTALL_DIR
export SYSTEMD_USER_DIR
export OLLAMA_USER_SERVICE_NAME
export OPENCLAW_SYSTEMD_SERVICE_NAME
export GENERATED_MODELFILE
export GENERATED_GGUF_LINK
export CURRENT_GGUF_FILE
export CURRENT_MODELFILE_FILE
export OLLAMA_SERVICE_MODE_FILE
export OPENCLAW_SERVICE_MODE_FILE
export OLLAMA_PID_FILE
export OPENCLAW_PID_FILE
export OLLAMA_LOG_FILE
export OPENCLAW_LOG_FILE
export OPENCLAW_GATEWAY_TOKEN_FILE
export OPENCLAW_STATE_HOME
export OPENCLAW_CONFIG_FILE
export OLLAMA_BASE_URL
export OPENCLAW_MODEL_REF
export OPENCLAW_UI_URL
